[NativeIFC] Python 3.11 Fix
yorikvanhavre/FreeCAD-NativeIFC pull request #61
Opened 2024-02-13 18:14 UTC by Syres916

Not sure but I really think this is what you actually intended?

2024-02-19 09:05 UTC, yorikvanhavre requested changes
Yes that's perfect! Thanks!

2024-02-19 09:05 UTC, yorikvanhavre commented on ifc_objects.py
> +            self.Type = state
this should be self.Type = _state, right?

```suggestion
            self.Type = _state
```

2024-02-19 18:56 UTC, Syres916 commented
Both `__setstate__` and `loads` functions should have the same arguments so the underscore has been removed, apologies.

2024-02-23 10:07 UTC, merged

2024-02-23 10:07 UTC, yorikvanhavre commented
Thanks!